app/models/breast_cancer.py
import pickle
import os
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Load the breast cancer dataset
data = load_breast_cancer()
X = data.data  # Features
y = data.target  # Labels

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Save the model as a pickle file in the specified directory
model_path = os.path.join('app\models', 'model.pkl')
with open(model_path, 'wb') as model_file:
    pickle.dump(model, model_file)

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt

# Import our app blueprints and config

from config import Config 


# Initialize extensions required for app
db = SQLAlchemy()
bcrypt = Bcrypt()

def create_app():
    app = Flask(__name__)
     
    # Load config
    # app.config.from_object('app.config.Config')
    app.config.from_object(Config)
     
    # Initialize app with extensions
    db.init_app(app)
    bcrypt.init_app(app)

    #register blueprints   
    from app.routes import main
    app.register_blueprint(main)
          
    #Global error handling
    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    return app

app/routes.py
from flask import Blueprint, render_template, flash, session, redirect, request, url_for
from app.db_models import User, CancerData
from app import db, bcrypt
from app.ml_models import predict 
#for test features list
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

main = Blueprint('main', __name__)

def login_required(f):
    def wrap(*args, **kwargs):
        if 'username' not in session:
            flash('You need to login first!', 'danger')
            return redirect(url_for('main.login')) 
        return f(*args, **kwargs)
    wrap.__name__ = f.__name__
    return wrap

def not_logged_in(f):
    def wrap(*args, **kwargs):
        if 'username' in session:
            flash('You are already logged in!', 'info')
            return redirect(url_for('main.input_data'))
        return f(*args, **kwargs)
    wrap.__name__ = f.__name__
    return wrap

@main.route('/')
def home():
    username = session.get('username', None)
    return render_template('home.html', username=username)

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']  

        # Check if the username is already registered
        existing_user = User.query.filter_by(username=username).first()
        if existing_user :
            flash('This username is already registered. Please log in or use a different username.', 'error')
            return redirect(url_for('main.register')) 
        
        #if the username doesn't exist
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')  
        new_user = User(username=username, password=hashed_password, email=email)

        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful, please log in.', 'success')

        return redirect(url_for('main.login'))  

    return render_template('register.html')

@main.route('/login', methods=['GET', 'POST'])
@not_logged_in
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email'] 
        
        user = User.query.filter_by(username=username).first()
        email = User.query.filter_by(email=email).first()
         
        if user and email and bcrypt.check_password_hash(user.password, password):
            session['username'] = user.username
            #flash('Login successful!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Login failed, check your username or password', 'danger')
        
    return render_template('login.html')

@main.route('/logout')
@login_required
def logout():
    session.pop('username', None)  
    #session.pop('password', None)  
    #session.pop('email', None)  
    
    flash('You have been logged out', 'info')
    return redirect(url_for('main.login')) 

@main.route('/input', methods=['GET', 'POST'])
@login_required
def input_data():  
    feature_names = data.feature_names
    print(feature_names)
    if request.method == 'POST':   
        #Extract features from the form
        features_value = [request.form[ft] for ft in feature_names] 
        # Make prediction
        prediction = predict([features_value])
        # Save the prediction to the database
        new_data = CancerData()
        new_data.mean_radius = features_value[0]
        new_data.mean_texture = features_value[1]
        new_data.mean_perimeter = features_value[2]
        new_data.mean_area = features_value[3]
        new_data.mean_smoothness = features_value[4]
        new_data.mean_compactness = features_value[5]
        new_data.mean_concavity = features_value[6]
        new_data.mean_concave_points = features_value[7]
        new_data.mean_symmetry = features_value[8]
        new_data.mean_fractal_dimension = features_value[9]
        new_data.radius_error = features_value[10]
        new_data.texture_error = features_value[11]
        new_data.perimeter_error = features_value[12]
        new_data.area_error = features_value[13]
        new_data.smoothness_error = features_value[14]
        new_data.compactness_error = features_value[15]
        new_data.concavity_error = features_value[16]
        new_data.concave_points_error = features_value[17]
        new_data.symmetry_error = features_value[18]
        new_data.fractal_dimension_error = features_value[19]
        new_data.worst_radius = features_value[20]
        new_data.worst_texture = features_value[21]
        new_data.worst_perimeter = features_value[22]
        new_data.worst_area = features_value[23]
        new_data.worst_smoothness = features_value[24]
        new_data.worst_compactness = features_value[25]
        new_data.worst_concavity = features_value[26]
        new_data.worst_concave_points = features_value[27]
        new_data.worst_symmetry = features_value[28]
        new_data.worst_fractal_dimension = features_value[29]
        new_data.prediction = "Malignant" if prediction[0] == 1 else "Benign"
        new_data.user = User.query.filter_by(username=session['username']).first()
        db.session.add(new_data)
        db.session.commit()
        return redirect(url_for('main.result'))
        # return render_template('result.html', output=prediction)
    
    return render_template('input.html',features=feature_names)

@main.route('/result')
@login_required
def result():
    user = User.query.filter_by(username=session['username']).first()
    prediction = user.features[-1].prediction
    return render_template('result.html', output=prediction)

@main.route('/profile')
@login_required
def profile():
    user = User.query.filter_by(username=session['username']).first()
    data_list = [{feature: getattr(d, str(feature).replace(' ', '_')) for feature in list(data.feature_names) + ['prediction']} for d in user.features] if user.features else []
    return render_template('profile.html', data=data_list, feature_names=data.feature_names)

#error handling only in main root
@main.errorhandler(404)
def page_not_found(error):

    return render_template('404.html', error_message="Something went wrong, page not found"), 404

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My Flask APP {% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='stylesheet2.css')}}">
</head>
<body>

<!-- Flask messages -->
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="mt-4">
        {% for category , message in messages %}
        <div class="alert alert-{{category}} alert-dismissable fade show" role="alert">
            {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
           
            {% endfor %}
        </div>

        {% endif %}
        {% endwith %}


        <!-- Page Content -->
        {% block content %}{% endblock %}


    </div>
    <!-- /.container -->
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='stylesheet.css')}}">

</head>
<body>
<div><img src="static/assets/img4.png" class="home_img"></div>
<div class="container text-center">
    <!--<h1>Breast Cancer Prediction </h1>-->
    <h4> This is a Smart Web Service with Docker Swarm</h4>
    {% if username %}
    <p>See previous prediction for logged-in users <a href="{{ url_for('main.profile') }}">profile link</a>
        or <a href="{{ url_for('main.input_data') }}">predict again</a>
        or <a href="{{ url_for('main.logout') }}">log out</a>
    </p>
    {% else %}
    <p>Welcome! Please <a href="{{ url_for('main.login') }}">log in</a> or <a href="{{ url_for('main.register') }}">register</a>
        to use the AI model.</p>
    {% endif %}
</div>
</body>
</html>

app/templates/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Input Model Features</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='stylesheet.css')}}">
</head>
<body class="img-background">
<!-- <img src="static/assets/img1.jpg" class="img"> -->

<div class="container box" style="width: 70%; height: 85%;">

    <h2 class="mt-5 ">Enter the Model Features</h2>

    <form method="POST">
        <div class="form-group">
            {% for ft in features %}
            <label>{{ft}}</label>
            <input type="text" class="form-control" name="{{ft}}" required>
            {% endfor %}
        </div>
        <p class=" container sticky_button">
            <button type="submit" class="btn btn-purple  "> Make Prediction</button>
        </p>

    </form>
     
</div>
<br>
<a href="{{ url_for('main.home') }}"  style="margin-left: 40px;"  class="btn btn-light-green">Back</a>
</body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container wrapper login-box">
    <h2 class="mt-5">Login</h2>
    <form method="POST">
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username" required>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password" required>
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p class="mt-2">Don't have an account? <a href="{{ url_for('main.register') }}">Register here</a>.</p>
</div>
{% endblock %}

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Profile</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='stylesheet.css')}}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

</head>
<body class="img-background">
<!-- <img src="static/assets/img1.jpg" class="img"> -->

<div class="container box" style="width: 100%; height: 85%;">

    <h2 class="mt-5 ">Profile</h2>

    <table class="table table-striped table-hover table-bordered custom-table">
        <thead>
            <tr>
                {% for feature in feature_names %}
                <th class="text-center">{{ feature }}</th>
                {% endfor %}
                <th class="text-center">Prediction</th>
            </tr>
        </thead>
        <tbody>
            {% for dd in data %}
            <tr>
                {% for feature in feature_names %}
                <td class="text-center">
                    {{ dd[feature] }}
                </td>
                {% endfor %}
                <td class="text-center">
                    {{ dd['prediction'] }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>

<br>
<a href="{{ url_for('main.home') }}"  style="margin-left: 40px;"  class="btn btn-light-green">Back</a>

</body>
</html>

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}

<div class="container mt-4">
<!-- Display Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
</div>

<div class="container wrapper login-box">
    <h2 class="mt-5">Register</h2>
    <form method="POST">
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username" required>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password" required>
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p class="mt-2">Already have an account? <a href="{{ url_for('main.login') }}">Login here</a>.</p>
</div>
{% endblock %}

app/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Prediction Result</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link  rel="stylesheet" href="{{url_for('static',filename='stylesheet.css')}}">

</head>
<body>
    <div class="container text-center">

        <div class="container mt-5">
 
         <div class="row align-items-center">
 
             <div class="col-md-6">
                 <h2 class="mt-5">The model Prediction:</h2>
                 {% if output[0]==0 %}
                 <p class="lead alert-warning"> <strong>it is symptoms of a malignant tumor</strong></p>
                 {% else %}
                 <p class="lead alert-info"> <strong>it is symptoms of a  benign tumor</strong></p>
                 {% endif %}
                 <br>
                 <p > 0 means malignant tumor, 1 mean benign tumor</p>
                 <a href="{{ url_for('main.input_data') }}" class="btn btn-pink">Predict Again</a>
             </div>
 
             <div class="col-md-6">
                 <img src="{{ url_for('static', filename='assets/img3.jpg') }}" class="img-fluid" alt="Result Image">
             </div>
 
         </div>
        </div>
     </div>
     <br>
     <a href="{{ url_for('main.home') }}"  style="margin-left: 40px;"  class="btn btn-light-green">Back</a>

</body>
</html>